
---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.Building

components:
  schemas:
    FishContainment:
      $ref: 'https://smart-data-models.github.io/dataModel.Aquaculture/FishContainment/model.yaml#/FishContainment'
info:
  description: |
    ...
  title: FishContainment
  version: 1.0.0
openapi: 3.0.0
paths:
  /ngsi-ld/v1/entities:
    get:
      description: Retrieve a set of entities which matches a specific query from an NGSI-LD system
      parameters:
        - in: query
          name: type
          required: true
          schema:
            enum:
              - FishContainment
            type: string
      responses:
        '200':
          content:
            application/ld+json:
              examples:
                keyvalues:
                  summary: Key-Values Pairs
                  value:
                    - $ref: 'https://smart-data-models.github.io/dataModel.Aquaculture/FishContainment/examples/example.json'
                normalized:
                  summary: Normalized NGSI-LD
                  value:
                    - $ref: 'https://smart-data-models.github.io/dataModel.Aquaculture/FishContainment/examples/example-normalized.jsonld'
          description: OK
      tags:
        - ngsi-ld
tags:
  - description: NGSI-LD Linked-data Format
    name: ngsi-ld
